# Generated by Django 3.2.4 on 2021-07-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ManyToManyField(to='payment.Product'),
        ),
    ]
